#
# Vagrantfile for FreeBSD 10.2 test environment.
#
Vagrant.configure(2) do |config|

  config.ssh.shell = 'sh'

  config.vm.box = 'freebsd/FreeBSD-10.2-RELEASE'

  # this box needs a MAC address
  config.vm.base_mac = '0800273E2877'

  # need enough memory to build syntex_syntax crate
  config.vm.provider 'virtualbox' do |vb|
    vb.memory = 2048
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true
  config.vbguest.auto_update = false

  # bring the system up to date
  config.vm.provision 'shell', privileged: false, inline: <<-SHELL
    sudo pkg update -q
    sudo pkg upgrade -q -y
    sudo pkg autoremove -y
    sudo pkg clean -y
  SHELL

end
